packages:
  - packages/*
  - examples/*
catalog:
  react: ^18.2.0
  react-dom: ^18.2.0
  '@types/react': ^18.2.38
  '@types/react-dom': ^18.2.16
  lodash-es: ^4.17.21
  normalize.css: ^8.0.1
  nprogress: ^0.2.0
  '@types/gulp': ^4.0.17
  '@types/gulp-autoprefixer': ^0.0.37
  '@types/gulp-concat': ^0.0.37
  '@types/gulp-less': ^0.0.36
  '@types/lodash-es': ^4.17.12
  '@types/nprogress': ^0.2.3
  '@typescript-eslint/eslint-plugin': ^6.21.0
  '@typescript-eslint/parser': ^6.21.0
  '@vitejs/plugin-legacy': ^5.4.1
  '@vitejs/plugin-react': ^4.2.0
  cross-env: ^7.0.3
  eslint: ^8.57.1
  eslint-plugin-react: ^7.37.4
  eslint-plugin-react-hooks: ^5.2.0
  gulp: ^5.0.0
  gulp-autoprefixer: ^9.0.0
  gulp-clean: ^0.4.0
  gulp-concat: ^2.6.1
  gulp-less: ^5.0.0
  '@rollup-plugin-terser': ^0.4.4
  terser: ^5.37.0
  typescript: ^5.7.2
  unocss: ^0.63.6
  unplugin-auto-import: ^0.18.6
  vite: ^5.2.0
  vite-plugin-dts: ^4.5.0
  less: ^4.2.0
  '@rollup/plugin-terser': ^0.4.4
  '@tarojs/components': 4.0.9
  '@tarojs/taro': 4.0.9
  '@antmjs/vantui': 3.6.3
  '@types/node': ^18
  '@babel/plugin-transform-modules-commonjs': ^7.27.1
  '@babel/plugin-transform-react-jsx': ^7.27.1
  '@babel/plugin-transform-runtime': ^7.27.1
  dayjs: ^1.11.13
  antd: 5.26.0-alpha.0
  '@ant-design/icons': ~5.6.1
  react-router-dom: ^7.6.1
  '@loadable/component': ^5.16.7
  '@types/loadable__component': ^5.13.9